feat: add callback function to pay()
interledgerjs/ilp-protocol-spsp pull request #5
Opened 2019-03-06 18:28 UTC by sabinebertram

Similar to the `pull()` functionality introduced in PR #4 , this adds a callback function to the `pay()` method. The arguments are `stream.totalSent` and `callbackOpts`, which are also passed into `pay()`.

2019-03-18 22:44 UTC, sharafian requested changes

2019-03-18 22:44 UTC, sharafian commented on index.js
> -    return Promise.race([
why is this logic changed?

2019-03-18 22:44 UTC, sharafian commented on index.js
> +      callback(payStream.totalSent, callbackOpts)
can we return these details instead of using a callback?

2019-03-21 21:44 UTC, sabinebertram commented
No longer necessary

2019-03-21 21:44 UTC, closed without merging